name       : xiphos
version    : 4.1.0
release    : 8
source     :
    - https://github.com/crosswire/xiphos/releases/download/4.1.0/xiphos-4.1.0.tar.gz : 52e2f415339b6ccef7049f5812707c617b4dbdb6ba40bf0f5a5210e04f75f849
license    : GPL-2.0-only
component  : office
summary    : Xiphos is a Bible study application
description: |
    Xiphos is a Bible study application
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(libgtkhtml-4.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rarian)
    - pkgconfig(sword)
    - pkgconfig(uuid)
    - pkgconfig(webkit2gtk-4.0)
    - biblesync-devel
    - intltool
    - rarian
setup      : |
    %waf_configure --enable-webkit2 --gtk=3
build      : |
    %waf_build
install    : |
    %waf_install
