name       : xiphos
version    : 4.0.7
release    : 3
source     :
    - https://github.com/crosswire/xiphos/releases/download/4.0.7/xiphos-4.0.7-20170924.tar.gz : 250eb7424e77c140f19bf6f38693ec40f04bb5cee8b6d5c3e25fea1a1bc2b028
license    : GPL-2.0
component  : office
summary    : Xiphos is a Bible study application
description: |
    Xiphos is a Bible study application
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(libgtkhtml-4.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rarian)
    - pkgconfig(sword)
    - pkgconfig(uuid)
    - pkgconfig(webkitgtk-3.0)
    - biblesync-devel
    - intltool
    - rarian
setup      : |
    ./waf configure --prefix=/usr --gtk=3
build      : |
    ./waf build
install    : |
    ./waf install --destdir=$installdir
