name       : xiphos
version    : 4.0.4
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/gnomesword/Xiphos/4.0.4/xiphos-4.0.4-20150830.tar.gz : 413bb8acb444946ccde1fb9fcfa3ff4bdb622cb56995b557f3215fab42193f20
license    : GPL-2.0
component  : office
summary    : Xiphos is a Bible study application
description: |
    Xiphos is a Bible study application
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libgsf-1)
    - pkgconfig(libgtkhtml-4.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rarian)
    - pkgconfig(sword)
    - pkgconfig(uuid)
    - pkgconfig(webkitgtk-3.0)
    - biblesync-devel
    - intltool
    - rarian
setup      : |
    ./waf configure --prefix=/usr --gtk=3
build      : |
    ./waf build
install    : |
    ./waf install --destdir=$installdir
